trigger:
- main  # Replace with the branch name you want to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@2
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    echo Installing dependencies...
    npm install -g live-server
  displayName: 'Install Live Server'

- script: |
    echo Starting the server to host HTML files...
    live-server --port=8080 --host=0.0.0.0 --open=./index.html
  displayName: 'Run HTML Project'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)
    artifact: html-files
    publishLocation: 'pipeline'
  displayName: 'Publish HTML files'
