# azure-pipelines.yml

trigger:
- main  # Automatically triggers the pipeline on changes to the 'main' branch. Update branch name if needed.

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image for the agent.

steps:
# Step 1: Checkout the code from the repository
- task: Checkout@1
  displayName: 'Checkout Repository'
  inputs:
    clean: true

# Step 2: Install live-server (a lightweight server for serving HTML files)
- script: |
    echo Installing live-server...
    npm install -g live-server
  displayName: 'Install live-server'

# Step 3: Start live-server to host your HTML project
- script: |
    echo Starting live-server...
    live-server --port=8080 --host=0.0.0.0 --open=index.html
  displayName: 'Serve HTML Project'

# Step 4: Optional - Publish files as a pipeline artifact for further usage or verification
- task: PublishPipelineArtifact@1
  displayName: 'Publish HTML Files as Artifact'
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)
    artifact: html-files
    publishLocation: 'pipeline'