trigger:
- main  # Adjust branch name if necessary

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Checkout code from the repository
- task: Checkout@1
  displayName: 'Checkout Repository'

# Step 2: Install live-server
- script: |
    echo Installing live-server...
    npm install -g live-server
  displayName: 'Install live-server'

# Step 3: Run live-server
- script: |
    echo Starting live-server...
    live-server --port=8080 --host=0.0.0.0 --open=index.html
  displayName: 'Serve HTML Project'

# Step 4: Publish pipeline artifact (optional)
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)  # Ensure this is valid
    artifact: html-files
    publishLocation: 'pipeline'
  displayName: 'Publish HTML Files as Artifact'
